import { t } from "@lingui/core/macro"
import { Trans } from "@lingui/react/macro"
import { EyeIcon, LoaderCircleIcon, RotateCcwIcon, SendIcon } from "lucide-react"
import type { ClientResponseError } from "pocketbase"
import { useEffect, useId, useMemo, useRef, useState } from "react"
import { badgeVariants } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Collapsible } from "@/components/ui/collapsible"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { toast } from "@/components/ui/use-toast"
import { pb } from "@/lib/api"
import type { NotificationTemplate, UserSettings } from "@/types"

/** Template related settings. Owned by the notifications page and persisted by its Save button. */
export interface NotificationTemplateSettings {
	templates: Record<string, NotificationTemplate>
	timezone: string
}

interface NotificationTemplatesProps extends NotificationTemplateSettings {
	onChange: (value: NotificationTemplateSettings) => void
}

/** Extracts the template settings from the stored user settings */
export function templateSettingsFromUser(userSettings: UserSettings): NotificationTemplateSettings {
	return {
		templates: userSettings.notificationTemplates ?? {},
		timezone: userSettings.notificationTimezone ?? "",
	}
}

/** Maps the template settings back to the user settings keys */
export function templateSettingsToUser(value: NotificationTemplateSettings): Partial<UserSettings> {
	return {
		notificationTemplates: value.templates,
		notificationTimezone: value.timezone,
	}
}

type TemplateField = "title" | "body"

interface PreviewResponse {
	title: string
	body: string
	err?: string
}

interface KindDef {
	kind: string
	name: () => string
	description: () => string
	/** kind specific placeholders, shown before the common ones */
	vars: string[]
	/** fixed values of {state} for this kind */
	states?: string[]
	/** description of {state} when it is not a fixed list */
	stateHint?: () => string
	/** close template equivalent of the built-in text (the real message is generated by code) */
	builtin: { title: string; body: string }
}

const PH = {
	link: "{link}",
	state: "{state}",
	stateMap: "{state:down=offline,up=online}",
	systemName: "{system.name}",
	time: "{time}",
	date: "{date}",
	clock: "{clock}",
}

/** Placeholders available in every template kind */
const COMMON_VARS = [
	"{title}",
	"{message}",
	"{link}",
	"{link_text}",
	"{state}",
	"{time}",
	"{date}",
	"{clock}",
	"{time_iso}",
	"{timezone}",
	"{system.name}",
	"{system.host}",
	"{system.port}",
	"{system.status}",
	"{system.hostname}",
	"{system.os}",
	"{system.kernel}",
	"{system.cpu}",
	"{system.cores}",
	"{system.arch}",
	"{system.agent_version}",
	"{system.uptime}",
]

const KINDS: KindDef[] = [
	{
		kind: "status",
		name: () => t`Status`,
		description: () => t`System goes down or comes back up.`,
		vars: [],
		states: ["down", "up"],
		builtin: {
			title: "Connection to {system.name} is {state}",
			body: "Connection to {system.name} is {state}\n\n{link}",
		},
	},
	{
		kind: "system",
		name: () => t`System (metrics)`,
		description: () => t`CPU, memory, disk, temperature, load, bandwidth, GPU and battery thresholds.`,
		vars: ["{metric}", "{descriptor}", "{value}", "{unit}", "{threshold}", "{minutes}"],
		states: ["above", "below"],
		builtin: {
			title: "{system.name} {metric} {state} threshold",
			body: "{descriptor} averaged {value}{unit} for the previous {minutes} minutes.\n\n{link}",
		},
	},
	{
		kind: "container",
		name: () => t`Container health`,
		description: () => t`Container health checks.`,
		vars: ["{containers}", "{count}", "{logs}"],
		states: ["unhealthy", "healthy"],
		builtin: {
			title: "{system.name} containers: {state}",
			body: "{state}: {containers}\n\n{logs}\n\n{link}",
		},
	},
	{
		kind: "smart",
		name: () => t`SMART`,
		description: () => t`Disk SMART status changes.`,
		vars: ["{device}", "{model}", "{old_state}", "{new_state}"],
		stateHint: () => t`the new SMART state`,
		builtin: {
			title: "SMART {new_state} on {system.name}: {device}",
			body: "Disk {device} ({model}) SMART status changed to {new_state}\n\n{link}",
		},
	},
	{
		kind: "systemd",
		name: () => t`Systemd services`,
		description: () => t`Systemd service failures and recoveries.`,
		vars: ["{services}", "{count}"],
		states: ["failed", "recovered"],
		builtin: {
			title: "Services {state} on {system.name}",
			body: "{count} services {state} on {system.name}: {services}\n\n{link}",
		},
	},
	{
		kind: "zfs",
		name: () => t`Storage pools`,
		description: () => t`Storage pool (ZFS, Btrfs) health changes.`,
		vars: ["{pool}", "{old_health}", "{new_health}"],
		stateHint: () => t`the new pool health`,
		builtin: {
			title: "Storage pool {new_health} on {system.name}: {pool}",
			body: "Storage pool {pool} ({system.name}) health changed from {old_health} to {new_health}\n\n{link}",
		},
	},
]

/** Small list used when Intl.supportedValuesOf is not available */
const FALLBACK_TIME_ZONES = [
	"UTC",
	"Europe/London",
	"Europe/Berlin",
	"Europe/Istanbul",
	"America/New_York",
	"America/Los_Angeles",
	"Asia/Tokyo",
	"Australia/Sydney",
]

const PREVIEW_ENDPOINT = "/api/beszel/notification-templates/preview"

/** Select value standing for "no timezone set" (the hub's own time zone is used) */
const HUB_TIME = "__hub__"

const MAX_TEMPLATE_CHARS = 2000

function getSupportedTimeZones(): string[] {
	try {
		if (typeof Intl.supportedValuesOf === "function") {
			return Intl.supportedValuesOf("timeZone")
		}
	} catch {
		// unsupported runtime
	}
	return []
}

function getBrowserTimeZone() {
	try {
		return Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC"
	} catch {
		return "UTC"
	}
}

function showError(msg?: string) {
	toast({
		title: t`Error`,
		description: msg || t`Failed to render template`,
		variant: "destructive",
	})
}

export function NotificationTemplates({ templates, timezone, onChange }: NotificationTemplatesProps) {
	const update = (patch: Partial<NotificationTemplateSettings>) => onChange({ templates, timezone, ...patch })

	// timezone: nothing is persisted until the user picks a zone; the hub's own
	// time zone (TZ) is used until then, and the browser zone is offered first
	const timeZones = useMemo(getSupportedTimeZones, [])
	const browserTimeZone = useMemo(getBrowserTimeZone, [])
	const timeZoneOptions = useMemo(() => {
		const zones = timeZones.length > 0 ? timeZones : FALLBACK_TIME_ZONES
		const extra = [timezone, browserTimeZone].filter((zone) => zone && !zones.includes(zone))
		const ordered = [browserTimeZone, ...zones.filter((zone) => zone !== browserTimeZone)]
		return [...extra.filter((zone) => zone !== browserTimeZone), ...ordered]
	}, [timeZones, timezone, browserTimeZone])
	const timeZoneId = useId()

	function setTemplateFields(kind: string, patch: Partial<NotificationTemplate>) {
		const next = { ...templates, [kind]: { ...templates[kind], ...patch } }
		if (!next[kind].title && !next[kind].body) {
			delete next[kind]
		}
		update({ templates: next })
	}

	function resetTemplate(kind: string) {
		const next = { ...templates }
		delete next[kind]
		update({ templates: next })
	}

	return (
		<div className="space-y-5">
			<div className="grid gap-2">
				<div className="mb-2">
					<h3 className="mb-1 text-lg font-medium">
						<Trans>Notification templates</Trans>
					</h3>
					<p className="text-sm text-muted-foreground leading-relaxed">
						<Trans>
							Customize the title and body of alert notifications. Placeholders such as {{ systemName: PH.systemName }}{" "}
							or {{ state: PH.state }} are replaced when the notification is sent; unknown placeholders are left as they
							are. Click a placeholder below a template to insert it at the cursor.
						</Trans>{" "}
						<Trans>
							See the{" "}
							<a
								href="https://beszel.dev/guide/notifications#custom-templates"
								className="link"
								target="_blank"
								rel="noopener"
							>
								documentation
							</a>{" "}
							for details.
						</Trans>
					</p>
					<p className="text-sm text-muted-foreground mt-1.5 leading-relaxed">
						<Trans>
							Each field shows the text currently in use: your own template, otherwise Beszel's built-in text. Edit it
							to customize it. When you use a custom body, the link to the system is not appended automatically, so
							include {{ link: PH.link }} yourself.
						</Trans>
					</p>
				</div>
				<Label className="block" htmlFor={timeZoneId}>
					<Trans>Timezone</Trans>
				</Label>
				{timeZones.length > 0 ? (
					<Select
						value={timezone || HUB_TIME}
						onValueChange={(value) => update({ timezone: value === HUB_TIME ? "" : value })}
					>
						<SelectTrigger id={timeZoneId}>
							<SelectValue placeholder={t`Select timezone`} />
						</SelectTrigger>
						<SelectContent>
							<SelectItem value={HUB_TIME}>
								<Trans comment="Timezone option: use the hub server's own time zone">Hub server time</Trans>
							</SelectItem>
							{timeZoneOptions.map((zone) => (
								<SelectItem key={zone} value={zone}>
									{zone}
								</SelectItem>
							))}
						</SelectContent>
					</Select>
				) : (
					<>
						<Input
							id={timeZoneId}
							list={`${timeZoneId}-list`}
							placeholder="Europe/Istanbul"
							value={timezone}
							onChange={(e) => update({ timezone: e.target.value })}
						/>
						<datalist id={`${timeZoneId}-list`}>
							{timeZoneOptions.map((zone) => (
								<option key={zone} value={zone} />
							))}
						</datalist>
					</>
				)}
				<p className="text-[0.8rem] text-muted-foreground">
					<Trans>
						Used for {{ time: PH.time }} / {{ date: PH.date }} / {{ clock: PH.clock }} in templates. Hub server time
						follows the hub's TZ environment variable.
					</Trans>{" "}
					<Trans>Your browser is in {browserTimeZone}.</Trans>
				</p>
			</div>
			<div className="grid gap-2.5">
				{KINDS.map((def) => (
					<TemplateCard
						key={def.kind}
						def={def}
						template={templates[def.kind]}
						timezone={timezone}
						onFieldChange={(patch) => setTemplateFields(def.kind, patch)}
						onReset={() => resetTemplate(def.kind)}
					/>
				))}
			</div>
		</div>
	)
}

interface TemplateCardProps {
	def: KindDef
	/** the user's own template for this kind (stored values) */
	template?: NotificationTemplate
	timezone: string
	onFieldChange: (patch: Partial<NotificationTemplate>) => void
	onReset: () => void
}

function TemplateCard({ def, template, timezone, onFieldChange, onReset }: TemplateCardProps) {
	const titleRef = useRef<HTMLInputElement>(null)
	const bodyRef = useRef<HTMLTextAreaElement>(null)
	const lastFocused = useRef<TemplateField>("body")
	const [preview, setPreview] = useState<PreviewResponse | null>(null)
	const [loading, setLoading] = useState<"preview" | "email" | null>(null)
	const id = useId()

	const stored = { title: template?.title ?? "", body: template?.body ?? "" }
	const customized = stored.title !== "" || stored.body !== ""
	// the fields show the text currently in use: the stored template, otherwise the built-in equivalent
	const title = stored.title || def.builtin.title
	const body = stored.body || def.builtin.body

	// a rendered preview is only valid for the text it was rendered from
	useEffect(() => setPreview(null), [stored.title, stored.body])

	/** Stores the edited text; text equal to the built-in equivalent is not a customization */
	function change(field: TemplateField, value: string) {
		onFieldChange({ [field]: value === def.builtin[field] ? "" : value })
	}

	/** Inserts a placeholder at the cursor of the last focused field */
	function insertPlaceholder(placeholder: string) {
		const field = lastFocused.current
		const el = field === "title" ? titleRef.current : bodyRef.current
		if (!el) {
			return
		}
		const value = field === "title" ? title : body
		const start = el.selectionStart ?? value.length
		const end = el.selectionEnd ?? start
		change(field, value.slice(0, start) + placeholder + value.slice(end))
		const cursor = start + placeholder.length
		requestAnimationFrame(() => {
			el.focus()
			el.setSelectionRange(cursor, cursor)
		})
	}

	async function render(sendEmail: boolean) {
		setLoading(sendEmail ? "email" : "preview")
		try {
			const res = await pb.send<PreviewResponse>(PREVIEW_ENDPOINT, {
				method: "POST",
				body: { kind: def.kind, title: stored.title, body: stored.body, timezone, sendEmail },
			})
			setPreview({ title: res.title ?? "", body: res.body ?? "" })
			if (sendEmail) {
				if (res.err) {
					showError(res.err)
				} else {
					toast({
						title: t`Test email sent`,
						description: t`Check your inbox`,
					})
				}
			}
		} catch (e: unknown) {
			showError((e as ClientResponseError).data?.message ?? (e as Error).message)
		} finally {
			setLoading(null)
		}
	}

	function reset() {
		setPreview(null)
		onReset()
	}

	return (
		<Collapsible
			title={
				<>
					{def.name()}
					{customized && (
						<span className={badgeVariants({ variant: "secondary", className: "font-normal" })}>
							<Trans comment="Notification template has custom content">Customized</Trans>
						</span>
					)}
				</>
			}
			description={def.description()}
		>
			<div className="grid gap-2">
				<Label htmlFor={`${id}-title`}>
					<Trans comment="Notification title">Title</Trans>
				</Label>
				<Input
					id={`${id}-title`}
					ref={titleRef}
					maxLength={MAX_TEMPLATE_CHARS}
					value={title}
					onFocus={() => {
						lastFocused.current = "title"
					}}
					onChange={(e) => change("title", e.target.value)}
				/>
			</div>
			<div className="grid gap-2">
				<Label htmlFor={`${id}-body`}>
					<Trans comment="Notification body">Body</Trans>
				</Label>
				<Textarea
					id={`${id}-body`}
					ref={bodyRef}
					rows={4}
					className="font-mono"
					maxLength={MAX_TEMPLATE_CHARS}
					value={body}
					onFocus={() => {
						lastFocused.current = "body"
					}}
					onChange={(e) => change("body", e.target.value)}
				/>
				<p className="text-[0.8rem] text-muted-foreground">
					<Trans>
						The built-in text shown here is a close equivalent, not an exact copy: the real message can vary slightly
						with the alert (counts, plurals, emoji). Use Preview to check the result.
					</Trans>
				</p>
			</div>
			<div className="grid gap-1.5">
				<span className="text-[0.8rem] text-muted-foreground">
					<Trans>Placeholders</Trans>
				</span>
				<div className="flex flex-wrap gap-1.5">
					{[...def.vars, ...COMMON_VARS].map((placeholder) => (
						<button
							key={placeholder}
							type="button"
							title={t`Insert placeholder`}
							className="rounded-md border bg-background px-1.5 py-0.5 font-mono text-xs hover:bg-accent/70 hover:text-accent-foreground focus-visible:outline-hidden focus-visible:ring-2 focus-visible:ring-ring"
							onMouseDown={(e) => e.preventDefault()}
							onClick={() => insertPlaceholder(placeholder)}
						>
							{placeholder}
						</button>
					))}
				</div>
				{(def.states || def.stateHint) && (
					<p className="text-[0.8rem] text-muted-foreground">
						<Trans comment="Followed by the possible values of the {state} placeholder">State values</Trans>:{" "}
						{def.states
							? def.states.map((state, i) => (
									<span key={state}>
										{i > 0 && ", "}
										<code>{state}</code>
									</span>
								))
							: def.stateHint?.()}
						{". "}
						<Trans>Change the wording inline, for example {{ stateMap: PH.stateMap }}.</Trans>
					</p>
				)}
			</div>
			<div className="flex flex-wrap gap-2">
				<Button type="button" variant="outline" disabled={loading !== null} onClick={() => render(false)}>
					{loading === "preview" ? (
						<LoaderCircleIcon className="h-4 w-4 animate-spin" />
					) : (
						<EyeIcon className="h-4 w-4" />
					)}
					<span className="ms-1.5">
						<Trans>Preview</Trans>
					</span>
				</Button>
				<Button type="button" variant="outline" disabled={loading !== null} onClick={() => render(true)}>
					{loading === "email" ? (
						<LoaderCircleIcon className="h-4 w-4 animate-spin" />
					) : (
						<SendIcon className="h-4 w-4" />
					)}
					<span className="ms-1.5">
						<Trans>Send test email</Trans>
					</span>
				</Button>
				<Button type="button" variant="outline" disabled={!customized} onClick={reset}>
					<RotateCcwIcon className="h-4 w-4" />
					<span className="ms-1.5">
						<Trans comment="Restore the built-in notification text">Reset</Trans>
					</span>
				</Button>
			</div>
			{preview && (
				<pre className="whitespace-pre-wrap break-words rounded-md border bg-background p-3 text-sm font-mono">
					<strong>{preview.title}</strong>
					{"\n"}
					{preview.body}
				</pre>
			)}
		</Collapsible>
	)
}
