version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: bun
    directory: /internal/site
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
