# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CmonitorAgent < Formula
  desc "Agent for CMonitor, a lightweight server monitoring platform."
  homepage "https://cmonitor.dev"
  version "0.10.3-dev.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyendkn/cmonitor/releases/download/v0.10.3-dev.7/cmonitor-agent_darwin_amd64.tar.gz"
      sha256 "d33f9f5b10e161dc582e1cd66b0e8ed4cc3b81c55d9eb1a5601641afa980531d"

      def install
        bin.install "cmonitor-agent"
        (bin/"cmonitor-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/cmonitor/cmonitor-agent.env" ]; then
            source "$HOME/.config/cmonitor/cmonitor-agent.env"
          fi
          set +a
          exec #{bin}/cmonitor-agent "$@"
        EOS
        (bin/"cmonitor-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyendkn/cmonitor/releases/download/v0.10.3-dev.7/cmonitor-agent_darwin_arm64.tar.gz"
      sha256 "f111058c4bd86f76225240a3dc73caa24d904ff0f80a9d0a7c61e35c664765ce"

      def install
        bin.install "cmonitor-agent"
        (bin/"cmonitor-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/cmonitor/cmonitor-agent.env" ]; then
            source "$HOME/.config/cmonitor/cmonitor-agent.env"
          fi
          set +a
          exec #{bin}/cmonitor-agent "$@"
        EOS
        (bin/"cmonitor-agent-launcher").chmod 0755
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/nguyendkn/cmonitor/releases/download/v0.10.3-dev.7/cmonitor-agent_linux_amd64.tar.gz"
      sha256 "24470377ceb5a8c0812b8e9a06938f4c46e1b553a5b85d24d5d3c0f45d095e24"
      def install
        bin.install "cmonitor-agent"
        (bin/"cmonitor-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/cmonitor/cmonitor-agent.env" ]; then
            source "$HOME/.config/cmonitor/cmonitor-agent.env"
          fi
          set +a
          exec #{bin}/cmonitor-agent "$@"
        EOS
        (bin/"cmonitor-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/nguyendkn/cmonitor/releases/download/v0.10.3-dev.7/cmonitor-agent_linux_arm.tar.gz"
      sha256 "4d117997114698582d7ab3aceb2b0d6c350c15bddae85f984eff371df7339635"
      def install
        bin.install "cmonitor-agent"
        (bin/"cmonitor-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/cmonitor/cmonitor-agent.env" ]; then
            source "$HOME/.config/cmonitor/cmonitor-agent.env"
          fi
          set +a
          exec #{bin}/cmonitor-agent "$@"
        EOS
        (bin/"cmonitor-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/nguyendkn/cmonitor/releases/download/v0.10.3-dev.7/cmonitor-agent_linux_arm64.tar.gz"
      sha256 "7ac9d61467bd7dbd7f4b4d1459c23f8e95f8dcc19f2dd6c9b389605512335d39"
      def install
        bin.install "cmonitor-agent"
        (bin/"cmonitor-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/cmonitor/cmonitor-agent.env" ]; then
            source "$HOME/.config/cmonitor/cmonitor-agent.env"
          fi
          set +a
          exec #{bin}/cmonitor-agent "$@"
        EOS
        (bin/"cmonitor-agent-launcher").chmod 0755
      end
    end
  end

  service do
    run ["#{bin}/cmonitor-agent-launcher"]
    log_path "#{Dir.home}/.cache/cmonitor/cmonitor-agent.log"
    error_log_path "#{Dir.home}/.cache/cmonitor/cmonitor-agent.log"
    keep_alive true
  end
end
