# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CmonitorAgent < Formula
  desc "Agent for CMonitor, a lightweight server monitoring platform."
  homepage "https://cmonitor.dev"
  version "0.10.3-dev.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyendkn/cmonitor/releases/download/v0.10.3-dev.5/cmonitor-agent_darwin_amd64.tar.gz"
      sha256 "0edbbf315576c6e0684ed09339d1b6e7591cc216cfc3d3bf70afb1f74d6a5ebb"

      def install
        bin.install "cmonitor-agent"
        (bin/"cmonitor-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/cmonitor/cmonitor-agent.env" ]; then
            source "$HOME/.config/cmonitor/cmonitor-agent.env"
          fi
          set +a
          exec #{bin}/cmonitor-agent "$@"
        EOS
        (bin/"cmonitor-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyendkn/cmonitor/releases/download/v0.10.3-dev.5/cmonitor-agent_darwin_arm64.tar.gz"
      sha256 "152f7c551481d0dccfa99c5805dc3f113f401107eb8c1197ac375d83017fcda5"

      def install
        bin.install "cmonitor-agent"
        (bin/"cmonitor-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/cmonitor/cmonitor-agent.env" ]; then
            source "$HOME/.config/cmonitor/cmonitor-agent.env"
          fi
          set +a
          exec #{bin}/cmonitor-agent "$@"
        EOS
        (bin/"cmonitor-agent-launcher").chmod 0755
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nguyendkn/cmonitor/releases/download/v0.10.3-dev.5/cmonitor-agent_linux_amd64.tar.gz"
        sha256 "6fd31522253cfa7cc9cef5506ddc306bded4392efac0d527527fea0b9431f781"

        def install
          bin.install "cmonitor-agent"
          (bin/"cmonitor-agent-launcher").write <<~EOS
            #!/bin/bash
            set -a
            if [ -f "$HOME/.config/cmonitor/cmonitor-agent.env" ]; then
              source "$HOME/.config/cmonitor/cmonitor-agent.env"
            fi
            set +a
            exec #{bin}/cmonitor-agent "$@"
          EOS
          (bin/"cmonitor-agent-launcher").chmod 0755
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/nguyendkn/cmonitor/releases/download/v0.10.3-dev.5/cmonitor-agent_linux_arm.tar.gz"
        sha256 "263956d7c379c6d00dbc8c8f8acc6e88fe33032b982b37e6a32291aa394e5ac0"

        def install
          bin.install "cmonitor-agent"
          (bin/"cmonitor-agent-launcher").write <<~EOS
            #!/bin/bash
            set -a
            if [ -f "$HOME/.config/cmonitor/cmonitor-agent.env" ]; then
              source "$HOME/.config/cmonitor/cmonitor-agent.env"
            fi
            set +a
            exec #{bin}/cmonitor-agent "$@"
          EOS
          (bin/"cmonitor-agent-launcher").chmod 0755
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nguyendkn/cmonitor/releases/download/v0.10.3-dev.5/cmonitor-agent_linux_arm64.tar.gz"
        sha256 "d58f9a35998a3991f90cf10e1f3c845947ca6b3019ae5fc4f92ec212076e665d"

        def install
          bin.install "cmonitor-agent"
          (bin/"cmonitor-agent-launcher").write <<~EOS
            #!/bin/bash
            set -a
            if [ -f "$HOME/.config/cmonitor/cmonitor-agent.env" ]; then
              source "$HOME/.config/cmonitor/cmonitor-agent.env"
            fi
            set +a
            exec #{bin}/cmonitor-agent "$@"
          EOS
          (bin/"cmonitor-agent-launcher").chmod 0755
        end
      end
    end
  end

  service do
    run ["#{bin}/cmonitor-agent-launcher"]
    log_path "#{Dir.home}/.cache/cmonitor/cmonitor-agent.log"
    error_log_path "#{Dir.home}/.cache/cmonitor/cmonitor-agent.log"
    keep_alive true
  end
end
