# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CmonitorAgent < Formula
  desc "Agent for CMonitor, a lightweight server monitoring platform."
  homepage "https://cmonitor.dev"
  version "0.11.1-dev.17"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyendkn/cmonitor/releases/download/v0.11.1-dev.17/cmonitor-agent_darwin_amd64.tar.gz"
      sha256 "a5cf7e8a8f3d163fe2078512776388524e683fd7db2beb95cbc2089d33585a51"

      def install
        bin.install "cmonitor-agent"
        (bin/"cmonitor-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/cmonitor/cmonitor-agent.env" ]; then
            source "$HOME/.config/cmonitor/cmonitor-agent.env"
          fi
          set +a
          exec #{bin}/cmonitor-agent "$@"
        EOS
        (bin/"cmonitor-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyendkn/cmonitor/releases/download/v0.11.1-dev.17/cmonitor-agent_darwin_arm64.tar.gz"
      sha256 "dee9c9686e2966ab19885709189eb3d03871b390187acd00665f02d7b27dbe5c"

      def install
        bin.install "cmonitor-agent"
        (bin/"cmonitor-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/cmonitor/cmonitor-agent.env" ]; then
            source "$HOME/.config/cmonitor/cmonitor-agent.env"
          fi
          set +a
          exec #{bin}/cmonitor-agent "$@"
        EOS
        (bin/"cmonitor-agent-launcher").chmod 0755
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/nguyendkn/cmonitor/releases/download/v0.11.1-dev.17/cmonitor-agent_linux_amd64.tar.gz"
      sha256 "9764584f91289b7d8d3f14fbe9e0748e3cb965e5662beb898e618266b1e12f63"
      def install
        bin.install "cmonitor-agent"
        (bin/"cmonitor-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/cmonitor/cmonitor-agent.env" ]; then
            source "$HOME/.config/cmonitor/cmonitor-agent.env"
          fi
          set +a
          exec #{bin}/cmonitor-agent "$@"
        EOS
        (bin/"cmonitor-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/nguyendkn/cmonitor/releases/download/v0.11.1-dev.17/cmonitor-agent_linux_arm.tar.gz"
      sha256 "f0f03b8ad0ccad2b6ed01fcbe7ae75c4508e22043915ceb1839b7f2e41446107"
      def install
        bin.install "cmonitor-agent"
        (bin/"cmonitor-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/cmonitor/cmonitor-agent.env" ]; then
            source "$HOME/.config/cmonitor/cmonitor-agent.env"
          fi
          set +a
          exec #{bin}/cmonitor-agent "$@"
        EOS
        (bin/"cmonitor-agent-launcher").chmod 0755
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/nguyendkn/cmonitor/releases/download/v0.11.1-dev.17/cmonitor-agent_linux_arm64.tar.gz"
      sha256 "067982a98c0cf5b0e49711417c168c0fd3f905af916f00e7c4896d5fd1fc00f4"
      def install
        bin.install "cmonitor-agent"
        (bin/"cmonitor-agent-launcher").write <<~EOS
          #!/bin/bash
          set -a
          if [ -f "$HOME/.config/cmonitor/cmonitor-agent.env" ]; then
            source "$HOME/.config/cmonitor/cmonitor-agent.env"
          fi
          set +a
          exec #{bin}/cmonitor-agent "$@"
        EOS
        (bin/"cmonitor-agent-launcher").chmod 0755
      end
    end
  end

  service do
    run ["#{bin}/cmonitor-agent-launcher"]
    log_path "#{Dir.home}/.cache/cmonitor/cmonitor-agent.log"
    error_log_path "#{Dir.home}/.cache/cmonitor/cmonitor-agent.log"
    keep_alive true
  end
end
