package migrations

import (
	"github.com/henrygd/beszel/internal/entities/speedtest"
	"github.com/pocketbase/pocketbase/core"
	m "github.com/pocketbase/pocketbase/migrations"
	"github.com/pocketbase/pocketbase/tools/types"
)

func init() {
	m.Register(func(app core.App) error {
		systems, err := app.FindCollectionByNameOrId("systems")
		if err != nil {
			return err
		}

		speedtests := core.NewBaseCollection("speedtests", "st_speedtests01")
		// IDs are stable hashes generated by the hub (see generateSpeedtestID).
		idField := speedtests.Fields.GetByName("id").(*core.TextField)
		idField.Min, idField.Max = 1, 10
		idField.AutogeneratePattern = "[a-z0-9]{10}"
		idField.Pattern = "^[a-z0-9]+$"
		speedtests.Fields.Add(
			&core.RelationField{Id: "st_system", Name: "system", CollectionId: systems.Id, CascadeDelete: true, MaxSelect: 1, Required: true},
			&core.NumberField{Id: "st_server_id", Name: "server_id", OnlyInt: true, Min: types.Pointer(0.0), Help: "Ookla server ID; empty selects a server automatically"},
			&core.NumberField{Id: "st_interval", Name: "interval", OnlyInt: true, Min: types.Pointer(float64(speedtest.MinInterval)), Max: types.Pointer(10080.0), Required: true, Help: "Minutes between runs"},
			&core.BoolField{Id: "st_enabled", Name: "enabled"},
			&core.NumberField{Id: "st_download", Name: "download", Help: "Bytes per second"},
			&core.NumberField{Id: "st_upload", Name: "upload", Help: "Bytes per second"},
			&core.NumberField{Id: "st_ping", Name: "ping", Help: "Milliseconds"},
			&core.NumberField{Id: "st_jitter", Name: "jitter", Help: "Milliseconds"},
			&core.NumberField{Id: "st_download_latency", Name: "download_latency", Help: "Interquartile mean latency during download in milliseconds"},
			&core.NumberField{Id: "st_download_jitter", Name: "download_jitter", Help: "Jitter during download in milliseconds"},
			&core.NumberField{Id: "st_upload_latency", Name: "upload_latency", Help: "Interquartile mean latency during upload in milliseconds"},
			&core.NumberField{Id: "st_upload_jitter", Name: "upload_jitter", Help: "Jitter during upload in milliseconds"},
			&core.NumberField{Id: "st_loss", Name: "loss", Help: "Packet loss percentage, -1 if unknown"},
			&core.TextField{Id: "st_server_name", Name: "server_name", Max: 200},
			&core.TextField{Id: "st_server_location", Name: "server_location", Max: 200},
			&core.TextField{Id: "st_isp", Name: "isp", Max: 200},
			&core.URLField{Id: "st_url", Name: "url"},
			&core.TextField{Id: "st_error", Name: "error", Max: 1000},
			&core.NumberField{Id: "st_last_run", Name: "last_run", OnlyInt: true, Help: "Unix milliseconds of the latest run"},
			&core.AutodateField{Id: "st_created", Name: "created", OnCreate: true},
			&core.DateField{Id: "st_updated", Name: "updated"},
		)
		speedtests.AddIndex("idx_st_system_enabled", false, "`system`, `enabled`", "")
		if err := app.Save(speedtests); err != nil {
			return err
		}

		stats := core.NewBaseCollection("speedtest_stats", "st_stats_00001")
		stats.Fields.Add(
			&core.RelationField{Id: "sts_system", Name: "system", CollectionId: systems.Id, CascadeDelete: true, MaxSelect: 1, Required: true},
			&core.RelationField{Id: "sts_speedtest", Name: "speedtest", CollectionId: speedtests.Id, CascadeDelete: true, MaxSelect: 1, Required: true},
			&core.NumberField{Id: "sts_created", Name: "created", OnlyInt: true, Help: "Unix milliseconds of the run"},
			&core.NumberField{Id: "sts_download", Name: "download", Help: "Bytes per second"},
			&core.NumberField{Id: "sts_upload", Name: "upload", Help: "Bytes per second"},
			&core.NumberField{Id: "sts_ping", Name: "ping", Help: "Milliseconds"},
			&core.NumberField{Id: "sts_jitter", Name: "jitter", Help: "Milliseconds"},
			&core.NumberField{Id: "sts_download_latency", Name: "download_latency", Help: "Interquartile mean latency during download in milliseconds"},
			&core.NumberField{Id: "sts_download_jitter", Name: "download_jitter", Help: "Jitter during download in milliseconds"},
			&core.NumberField{Id: "sts_upload_latency", Name: "upload_latency", Help: "Interquartile mean latency during upload in milliseconds"},
			&core.NumberField{Id: "sts_upload_jitter", Name: "upload_jitter", Help: "Jitter during upload in milliseconds"},
			&core.NumberField{Id: "sts_loss", Name: "loss", Help: "Packet loss percentage, -1 if unknown"},
			&core.NumberField{Id: "sts_server_id", Name: "server_id", OnlyInt: true},
			&core.TextField{Id: "sts_server_name", Name: "server_name", Max: 200},
			&core.URLField{Id: "sts_url", Name: "url"},
			&core.TextField{Id: "sts_error", Name: "error", Max: 1000, Help: "Set when the run failed; measurements are then empty"},
		)
		stats.AddIndex("idx_sts_speedtest_created", false, "`speedtest`, `created`", "")
		stats.AddIndex("idx_sts_created", false, "`created`", "")
		return app.Save(stats)
	}, func(app core.App) error {
		for _, name := range []string{"speedtest_stats", "speedtests"} {
			collection, err := app.FindCollectionByNameOrId(name)
			if err != nil {
				continue
			}
			if err := app.Delete(collection); err != nil {
				return err
			}
		}
		return nil
	})
}
