name: 🐛 Bug report
description: Use this template to report a bug or issue.
title: '[Bug]: '
labels: ['bug']
body:
  - type: checkboxes
    attributes:
      label: Welcome!
      description: |
        The issue tracker is for reporting bugs and feature requests only. For end-user related support questions, please use the **[GitHub Discussions](https://github.com/henrygd/beszel/discussions/new?category=support)** instead

        Please note:
        - For translation-related issues or requests, please use the [Crowdin project](https://crowdin.com/project/beszel).
        - To request a change or feature, use the [feature request form](https://github.com/henrygd/beszel/issues/new?template=feature_request.yml).
        - Any issues that can be resolved by consulting the documentation or by reviewing existing open or closed issues will be closed.
        **- Please do not submit bugs that are specific to ZFS. We plan to add integration with ZFS utilities in the near future.**

      options:
      - label: I have read the [Documentation](https://beszel.dev/guide/getting-started)
        required: true
      - label: I have checked the [Common Issues Guide](https://beszel.dev/guide/common-issues) and my problem was not mentioned there.
        required: true
      - label: I have searched open and closed issues and my problem was not mentioned before.
        required: true
      - label: I have verified I am using the latest version available. You can check the latest release [here](https://github.com/henrygd/beszel/releases).
        required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Beszel is this about?
      options:
        - Hub
        - Agent
        - Hub & Agent
      default: 0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Problem Description
      description: |
        How to write a good bug report?

        - Respect the issue template as much as possible.
        - The title should be short and descriptive.
        - Explain the conditions which led you to report this issue: the context.
        - The context should lead to something, a problem that you’re facing.
        - Remain clear and concise.
        - Format your messages to help the reader focus on what matters and understand the structure of your message, use [Markdown syntax](https://help.github.com/articles/github-flavored-markdown)
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: |
        In a perfect world, what should have happened?
        **Important:** Be specific. Vague descriptions like "it should work" are not helpful.
      placeholder: When I got to the coffee pot, it should have been full.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        Provide detailed, numbered steps that someone else can follow to reproduce the issue.
        **Important:** Vague descriptions like "it doesn't work" or "it's broken" will result in the issue being closed.
        Include specific actions, URLs, button clicks, and any relevant data or configuration.
      placeholder: |
        1. Go to the coffee pot.
        2. Make more coffee.
        3. Pour it into a cup.
        4. Observe that the cup is empty instead of full.
    validations:
      required: true

  - type: input
    id: system
    attributes:
      label: OS / Architecture
      placeholder: linux/amd64 (agent), freebsd/arm64 (hub)
    validations:
      required: true
  
  - type: input
    id: version
    attributes:
      label: Beszel version
      placeholder: 0.9.1
    validations:
      required: true
  
  - type: dropdown
    id: install-method
    attributes:
      label: Installation method
      options:
        - Docker
        - Binary
        - Nix
        - Unraid
        - Coolify
        - Other (please describe above)
    validations:
      required: true
  
  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Please provide any relevant service configuration
      render: yaml
  
  - type: textarea
    id: hub-logs
    attributes:
      label: Hub Logs
      description: Check the logs page in PocketBase (`/_/#/logs`) for relevant errors (copy JSON).
      render: json
  
  - type: textarea
    id: agent-logs
    attributes:
      label: Agent Logs
      description: Please provide any logs from the agent, if relevant. Use `LOG_LEVEL=debug` for more info.
      render: shell
