name: 🚀 Feature request
description: Request a new feature or change.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: checkboxes
    attributes:
      label: Welcome!
      description: |
        The issue tracker is for reporting bugs and feature requests only. For end-user related support questions, please use the **[GitHub Discussions](https://github.com/henrygd/beszel/discussions)** instead

        Please note:
        - For **Bug reports**, use the [Bug Form](https://github.com/henrygd/beszel/issues/new?template=bug_report.yml).
        - Any requests for new translations should be requested within the [crowdin project](https://crowdin.com/project/beszel).
        - Create one issue per feature request. This helps us keep track of requests and prioritize them accordingly.

      options:
      - label: I have searched open and closed feature requests to make sure this or similar feature request does not already exist.
        required: true
      - label: This is a feature request, not a bug report or support question.
        required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Beszel is this about?
      options:
        - Hub
        - Agent
        - Hub & Agent
      default: 0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Describe the solution or feature you'd like. Explain what problem this solves or what value it adds.
        **Important:** Be specific and detailed. Vague requests like "make it better" will be closed.
      placeholder: |
        Example:
        - What is the feature?
        - What problem does it solve?
        - How should it work?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation / Use Case
      description: Why do you want this feature? What problem does it solve?
    validations:
      required: true