# Specialized images available for Nvidia / Intel GPUs
#
# Docs: https://beszel.dev/guide/agent-installation
# Env vars: https://beszel.dev/guide/environment-variables

services:
  beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./beszel_agent_data:/var/lib/beszel-agent
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk1/.beszel:/extra-filesystems/disk1:ro
    environment:
      LISTEN: 45876
      KEY: "<public key>"
      HUB_URL: "<hub url>"
      TOKEN: "<token>"
    # healthcheck:
    #   test: ['CMD', '/agent', 'health']
    #   interval: 120s
