version: 2

project_name: cmonitor

before:
  hooks:
    - go mod tidy

builds:
  - id: cmonitor-hub
    binary: cmonitor-hub
    main: cmd/hub/hub.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm

  - id: cmonitor-agent
    binary: cmonitor-agent
    main: cmd/agent/agent.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
      - openbsd
      - windows
    goarch:
      - amd64
      - arm64
      - arm
      - mips64
      - riscv64
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: openbsd
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: riscv64
      - goos: windows
        goarch: riscv64

archives:
  - id: cmonitor-agent
    format: tar.gz
    builds:
      - cmonitor-agent
    name_template: >-
      {{ .Binary }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip

  - id: cmonitor-hub
    format: tar.gz
    builds:
      - cmonitor-hub
    name_template: >-
      {{ .Binary }}_
      {{- .Os }}_
      {{- .Arch }}

nfpms:
  - id: cmonitor-agent
    package_name: cmonitor-agent
    description: |-
      Agent for CMonitor
      CMonitor is a lightweight server monitoring platform that includes Docker
      statistics, historical data, and alert functions. It has a friendly web
      interface, simple configuration, and is ready to use out of the box.
      It supports automatic backup, multi-user, OAuth authentication, and
      API access.
    maintainer: nguyendkn <dknguyen2304@gmail.com>
    section: net
    builds:
      - cmonitor-agent
    formats:
      - deb
    # don't think this is needed with CGO_ENABLED=0
    # dependencies:
    #   - libc6
    contents:
      - src: ../supplemental/debian/cmonitor-agent.service
        dst: lib/systemd/system/cmonitor-agent.service
        packager: deb
      - src: ../supplemental/debian/copyright
        dst: usr/share/doc/cmonitor-agent/copyright
        packager: deb
      - src: ../supplemental/debian/lintian-overrides
        dst: usr/share/lintian/overrides/cmonitor-agent
        packager: deb
    scripts:
      postinstall: ../supplemental/debian/postinstall.sh
      preremove: ../supplemental/debian/prerm.sh
      postremove: ../supplemental/debian/postrm.sh
    deb:
      predepends:
        - adduser
        - debconf
      scripts:
        templates: ../supplemental/debian/templates
        # Currently broken due to a bug in goreleaser
        # https://github.com/goreleaser/goreleaser/issues/5487
        #config: ../supplemental/debian/config.sh

scoops:
  - ids: [cmonitor-agent]
    name: cmonitor-agent
    repository:
      owner: nguyendkn
      name: cmonitor
    homepage: 'https://cmonitor.dev'
    description: 'Agent for CMonitor, a lightweight server monitoring platform.'
    license: MIT

# # Needs choco installed, so doesn't build on linux / default gh workflow :(
# chocolateys:
#   - title: CMonitor Agent
#     ids: [cmonitor-agent]
#     package_source_url: https://github.com/nguyendkn/cmonitor-chocolatey
#     owners: nguyendkn
#     authors: nguyendkn
#     summary: 'Agent for Beszel, a lightweight server monitoring platform.'
#     description: |
#       Beszel is a lightweight server monitoring platform that includes Docker statistics, historical data, and alert functions.

#       It has a friendly web interface, simple configuration, and is ready to use out of the box. It supports automatic backup, multi-user, OAuth authentication, and API access.
#     license_url: https://github.com/nguyendkn/beszel/blob/main/LICENSE
#     project_url: https://beszel.dev
#     project_source_url: https://github.com/nguyendkn/beszel
#     docs_url: https://beszel.dev/guide/getting-started
#     icon_url: https://cdn.jsdelivr.net/gh/selfhst/icons/png/beszel.png
#     bug_tracker_url: https://github.com/nguyendkn/beszel/issues
#     copyright: 2025 nguyendkn
#     tags: foss cross-platform admin monitoring
#     require_license_acceptance: false
#     release_notes: 'https://github.com/nguyendkn/beszel/releases/tag/v{{ .Version }}'

brews:
  - ids: [cmonitor-agent]
    name: cmonitor-agent
    repository:
      owner: nguyendkn
      name: cmonitor
    homepage: 'https://cmonitor.dev'
    description: 'Agent for CMonitor, a lightweight server monitoring platform.'
    license: MIT
    extra_install: |
      (bin/"cmonitor-agent-launcher").write <<~EOS
        #!/bin/bash
        set -a
        if [ -f "$HOME/.config/cmonitor/cmonitor-agent.env" ]; then
          source "$HOME/.config/cmonitor/cmonitor-agent.env"
        fi
        set +a
        exec #{bin}/cmonitor-agent "$@"
      EOS
      (bin/"cmonitor-agent-launcher").chmod 0755
    service: |
      run ["#{bin}/cmonitor-agent-launcher"]
      log_path "#{Dir.home}/.cache/cmonitor/cmonitor-agent.log"
      error_log_path "#{Dir.home}/.cache/cmonitor/cmonitor-agent.log"
      keep_alive true

release:
  draft: true

changelog:
  disable: true
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
