FROM --platform=$BUILDPLATFORM golang:alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
# RUN go mod download
COPY *.go ./
COPY cmd ./cmd
COPY internal ./internal

# Build
ARG TARGETOS TARGETARCH
RUN GOGC=75 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -ldflags "-w -s" -o /agent ./cmd/agent

# ? -------------------------
FROM scratch

COPY --from=builder /agent /agent

ENTRYPOINT ["/agent"]