FROM --platform=$BUILDPLATFORM golang:alpine AS builder

WORKDIR /app

COPY ../go.mod ../go.sum ./
RUN go mod download

# Copy source files
COPY . ./

# Build
ARG TARGETOS TARGETARCH
RUN CGO_ENABLED=0 GOGC=75 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -ldflags "-w -s" -o /agent ./internal/cmd/agent

RUN rm -rf /tmp/*

# --------------------------
# Final image: default scratch-based agent
# --------------------------
FROM alpine:3.23
COPY --from=builder /agent /agent

# AMD GPU name lookup (used by agent on Linux when /usr/share/libdrm/amdgpu.ids is read)
COPY --from=builder /app/agent/test-data/amdgpu.ids /usr/share/libdrm/amdgpu.ids

RUN apk add --no-cache smartmontools

# Ensure data persistence across container recreations
VOLUME ["/var/lib/beszel-agent"]

ENTRYPOINT ["/agent"]