FROM --platform=$BUILDPLATFORM golang:alpine AS builder

WORKDIR /app

COPY ../go.mod ../go.sum ./
RUN go mod download

# Copy source files
COPY . ./

# Build
ARG TARGETOS TARGETARCH
RUN CGO_ENABLED=0 GOGC=75 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -ldflags "-w -s" -o /agent ./internal/cmd/agent

# --------------------------
# Final image: default scratch-based agent
# Note: must cap_add: [CAP_PERFMON] in docker-compose.yml
# --------------------------
FROM alpine:edge

COPY --from=builder /agent /agent

RUN apk add --no-cache -X https://dl-cdn.alpinelinux.org/alpine/edge/testing igt-gpu-tools

ENTRYPOINT ["/agent"]