// Package speedtest defines the speedtest configuration and results exchanged between hub and agent.
package speedtest

import "github.com/henrygd/beszel/internal/entities/monitor"

// MinInterval is the shortest allowed interval between speedtest runs, in minutes.
const MinInterval = 15

// Config defines a scheduled speedtest sent from hub to agent.
type Config struct {
	// ID is the stable speedtests record ID generated by the hub.
	ID string `cbor:"0,keyasint"`
	// ServerID is the Ookla server to test against. Zero selects a server automatically.
	ServerID uint32 `cbor:"1,keyasint,omitempty"`
	// Interval is the time between runs in minutes.
	Interval uint32 `cbor:"2,keyasint"`
	// Interface is the network interface to bind to. Empty uses the default route.
	Interface string `cbor:"3,keyasint,omitempty"`
}

// SyncRequest defines an incremental or full speedtest sync request sent to the agent.
// RunNow starts a run in the background; its result is reported with the next stats.
type SyncRequest struct {
	Action  monitor.SyncAction `cbor:"0,keyasint"`
	Config  Config             `cbor:"1,keyasint,omitempty"`
	Configs []Config           `cbor:"2,keyasint,omitempty"`
	RunNow  bool               `cbor:"3,keyasint,omitempty"`
}

// Result holds the outcome of the latest speedtest run.
type Result struct {
	// RunAt is the Unix timestamp in milliseconds when the run finished.
	RunAt int64 `cbor:"0,keyasint"`
	// Download and Upload are bandwidths in bytes per second.
	Download uint64 `cbor:"1,keyasint,omitempty"`
	Upload   uint64 `cbor:"2,keyasint,omitempty"`
	// Ping and Jitter are idle latencies in milliseconds.
	Ping   float64 `cbor:"3,keyasint,omitempty"`
	Jitter float64 `cbor:"4,keyasint,omitempty"`
	// Loss is the packet loss percentage (0-100), or -1 when the server does not report it.
	Loss           float64 `cbor:"5,keyasint,omitempty"`
	ServerID       uint32  `cbor:"6,keyasint,omitempty"`
	ServerName     string  `cbor:"7,keyasint,omitempty"`
	ServerLocation string  `cbor:"8,keyasint,omitempty"`
	ISP            string  `cbor:"9,keyasint,omitempty"`
	// URL links to the result on speedtest.net.
	URL string `cbor:"10,keyasint,omitempty"`
	// Error is set when the run failed; other measurement fields are then empty.
	Error string `cbor:"11,keyasint,omitempty"`
	// DownloadLatency and UploadLatency are latencies measured while the connection is loaded.
	DownloadLatency Latency `cbor:"14,keyasint,omitempty"`
	UploadLatency   Latency `cbor:"15,keyasint,omitempty"`
}

// Latency summarizes latencies in milliseconds measured during a download or upload.
type Latency struct {
	// IQM is the interquartile mean, which excludes outliers.
	IQM    float64 `cbor:"0,keyasint,omitempty"`
	Jitter float64 `cbor:"3,keyasint,omitempty"`
}
