services:
  cmonitor-hub:
    image: 'nguyendkn/cmonitor-hub'
    container_name: 'cmonitor-hub'
    restart: unless-stopped
    ports:
      - '8090:8090'
    volumes:
      - ./cmonitor_data:/cmonitor_data
