# Docs: https://beszel.dev/guide/hub-installation
# Env vars: https://beszel.dev/guide/environment-variables

services:
  beszel:
    image: "henrygd/beszel"
    container_name: "beszel"
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./beszel_data:/beszel_data
    # healthcheck:
    #   test: ['CMD', '/beszel', 'health', '--url', 'http://localhost:8090']
    #   interval: 120s
    #   start_period: 10s
    #   timeout: 5s
