name: Build CMonitor site

on:
  push:
    branches: [main]

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --no-save --cwd ./beszel/site

      - name: Build site
        run: bun run --cwd ./beszel/site build

      - name: Upload built site
        uses: actions/upload-artifact@v4
        with:
          name: site-dist
          path: ./beszel/site/dist
